[project]
name = "penguins-classification"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn>=0.30.0",
    "seaborn>=0.13.0",
    "pandas>=2.2.0",
    "scikit-learn>=1.5.0",
    "xgboost>=2.1.0",
    "pydantic>=2.9.0"
]
[tool.uv]
dev-dependencies = []